apiVersion: v1
kind: Service
metadata:
  name: judge0
  labels:
    app: judge0
spec:
  type: {{.Values.service.type}}
  ports:
    - port: {{.Values.service.port}}
      targetPort: 80
  selector:
    app: judge0
