apiVersion: v1
kind: Service
metadata:
  name: flask
spec:
  type: {{.Values.service.flask.type}}
  ports:
    - protocol: TCP
      port: {{.Values.service.flask.port}}
      targetPort: 5000
      nodePort: 32222
  selector:
    app: flask
status:
  loadBalancer: {}
