apiVersion: apps/v1
kind: Deployment
metadata:
  name: judge0-server
  labels:
    app: judge0-server
spec:
  replicas: {{.Values.replicaCount}}
  selector:
    matchLabels:
      app: judge0-server
  template:
    metadata:
      labels:
        app: judge0-server
    spec:
      containers:
        - name: judge0-server
          image: "{{ .Values.image.judge0.repository }}:{{ .Values.image.judge0.tag }}"
          imagePullPolicy: "{{ .Values.image.judge0.pullPolicy }}"
          ports:
            {{- range .Values.service.judge0.server.ports }}
            - containerPort: {{ .containerPort }}
              hostPort: {{ .hostPort }}
              name: {{ .name }}
            {{- end }}
          envFrom:
            - configMapRef:
                name: judge0-config
          securityContext:
            privileged: true
          resources:
            requests:
              memory: "512Mi"
              cpu: "500m"
            limits:
              memory: "2Gi"
              cpu: "2"
      tolerations:
        - key: "instance_type"
          operator: "Equal"
          value: "spot"
          effect: "NoSchedule"
