apiVersion: v1
kind: Service
metadata:
  name: judge0-server
  labels:
    app: judge0-server
spec:
  type: {{.Values.service.judge0.type}}
  ports:
    {{- range .Values.service.judge0.server.ports }}
    - port: {{ .containerPort }}
      targetPort: {{ .containerPort }}
      protocol: TCP
      name: {{ .name }}
    {{- end }}
  selector:
    app: judge0-server
