apiVersion: v1
kind: ConfigMap
metadata:
  name: judge0-config
data:
  JUDGE0_TELEMETRY_ENABLE: "{{ .Values.env.judge0.JUDGE0_TELEMETRY_ENABLE }}"
  ENABLE_WAIT_RESULT: "{{ .Values.env.judge0.ENABLE_WAIT_RESULT }}"
  ENABLE_COMPILER_OPTIONS: "{{ .Values.env.judge0.ENABLE_COMPILER_OPTIONS }}"
  ENABLE_COMMAND_LINE_ARGUMENTS: "{{ .Values.env.judge0.ENABLE_COMMAND_LINE_ARGUMENTS }}"
  SUBMISSION_CACHE_DURATION: "{{ .Values.env.judge0.SUBMISSION_CACHE_DURATION }}"
  INTERVAL: "{{ .Values.env.judge0.INTERVAL }}"
  COUNT: "{{ .Values.env.judge0.COUNT }}"
  MAX_QUEUE_SIZE: "{{ .Values.env.judge0.MAX_QUEUE_SIZE }}"
  RAILS_ENV: "{{ .Values.env.judge0.RAILS_ENV }}"
  REDIS_HOST: "{{ .Values.env.redis.HOST }}"
  REDIS_PORT: "{{ .Values.env.redis.PORT }}"
  REDIS_PASSWORD: "{{ .Values.env.redis.PASSWORD }}"
  POSTGRES_HOST: "{{ .Values.env.postgres.HOST }}"
  POSTGRES_PORT: "{{ .Values.env.postgres.PORT }}"
  POSTGRES_USER: "{{ .Values.env.postgres.USER }}"
  POSTGRES_PASSWORD: "{{ .Values.env.postgres.PASSWORD }}"
  POSTGRES_DB: "{{ .Values.env.judge0.DATABASE_NAME }}"
