apiVersion: apps/v1
kind: Deployment
metadata:
  name: judge0-worker
  labels:
    app: judge0-worker
spec:
  replicas: {{.Values.replicaCount}}
  selector:
    matchLabels:
      app: judge0-worker
  template:
    metadata:
      labels:
        app: judge0-worker
    spec:
      containers:
        - name: judge0-worker
          image: "{{ .Values.image.judge0.repository }}:{{ .Values.image.judge0.tag }}"
          imagePullPolicy: "{{ .Values.image.judge0.pullPolicy }}"
          env:
            - name: SYSTEMD_CGROUP_ENABLE_LEGACY_FORCE
              value: "1"
          envFrom:
            - configMapRef:
                name: judge0-config
          command: [./scripts/workers"]
          securityContext:
            privileged: true
          resources:
            requests:
              memory: "512Mi"
              cpu: "500m"
            limits:
              memory: "2Gi"
              cpu: "2"
      tolerations:
        - key: "instance_type"
          operator: "Equal"
          value: "spot"
          effect: "NoSchedule"
