apiVersion: apps/v1
kind: Deployment
metadata:
  name: judge0
  labels:
    app: judge0
spec:
  replicas: { { .Values.replicaCount } }
  selector:
    matchLabels:
      app: judge0
  template:
    metadata:
      labels:
        app: judge0
    spec:
      containers:
        - name: judge0
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: "{{ .Values.image.pullPolicy }}"
          ports:
            - containerPort: 80
          envFrom:
            - configMapRef:
                name: judge0-config
